### ISSUE TITLE
go install issue

### ISSUE THREAD

**Issue by araskachoi** [whiteblock/genesis-cli#9]
```
daniel:genesis-cli danielchoi$ go install github.com/whiteblock/genesis-cli
can't load package: package github.com/whiteblock/genesis-cli: cannot find module providing package github.com/whiteblock/genesis-cli
```
step 1:  git clone https://github.com/whiteblock/genesis-cli.git
step 2: cd genesis-cli/
step 3: go install github.com/whiteblock/genesis-cli (error)

**Comment by n8wb** [comment]
You should install it using the installation script `curl -sSf https://assets.whiteblock.io/cli/install.sh | sh` rather than using go install. Doing so will ensure that the binary is inside your PATH. If you really must install it manually, I would suggest running `make install` inside the repo.
